// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMOVIA.Entities.Entities
{
    public partial class tbCargos
    {
        public tbCargos()
        {
            tbColaboradores = new HashSet<tbColaboradores>();
        }

        public int carg_Id { get; set; }
        public string carg_Descripcion { get; set; }
        public int carg_UsuarioCreacion { get; set; }
        public DateTime carg_FechaCreacion { get; set; }
        public int? carg_UsuarioModificacion { get; set; }
        public DateTime? carg_FechaModificacion { get; set; }
        public bool? carg_Estado { get; set; }

        public virtual tbUsuarios carg_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbColaboradores> tbColaboradores { get; set; }
    }
}