// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMOVIA.Entities.Entities
{
    public partial class tbColaboradoresPorSucursal
    {
        public int cosu_Id { get; set; }
        public int? cosu_Distanciakm { get; set; }
        public int? cola_Id { get; set; }
        public int? sucu_Id { get; set; }

        public virtual tbColaboradores cola { get; set; }
        public virtual tbSucursales sucu { get; set; }
    }
}