// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMOVIA.Entities.Entities
{
    public partial class tbColaboradores
    {
        public tbColaboradores()
        {
            tbColaboradoresPorSucursal = new HashSet<tbColaboradoresPorSucursal>();
            tbUsuarios = new HashSet<tbUsuarios>();
            tbViajesDetalle = new HashSet<tbViajesDetalle>();
        }

        //PARA LISTAR
        public string codigo { get; set; }
        public string colaborador { get; set; }
        public string edad { get; set; }
        public string municipio { get; set; }
        public string estadocivil { get; set; }
        public string cargo { get; set; }
        public string usuarioCreacion { get; set; }
        public string usuarioModificacion { get; set; }

        //TABLA
        public int cola_Id { get; set; }
        public string cola_DNI { get; set; }
        public string cola_Nombres { get; set; }
        public string cola_Apellidos { get; set; }
        public string cola_CorreoElectronico { get; set; }
        public string cola_Telefono { get; set; }
        public string cola_Sexo { get; set; }
        public DateTime cola_FechaNacimiento { get; set; }
        public string cola_ObservacionActivar { get; set; }
        public string cola_ObservacionInactivar { get; set; }
        public int muni_Id { get; set; }
        public int civi_Id { get; set; }
        public int carg_Id { get; set; }
        public int cola_UsuarioCreacion { get; set; }
        public DateTime? cola_FechaCreacion { get; set; }
        public int? cola_UsuarioModificacion { get; set; }
        public DateTime? cola_FechaModificacion { get; set; }
        public bool? cola_Estado { get; set; }

        public virtual tbCargos carg { get; set; }
        public virtual tbEstadosCiviles civi { get; set; }
        public virtual tbUsuarios cola_UsuarioModificacionNavigation { get; set; }
        public virtual tbMunicipios muni { get; set; }
        public virtual ICollection<tbColaboradoresPorSucursal> tbColaboradoresPorSucursal { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
        public virtual ICollection<tbViajesDetalle> tbViajesDetalle { get; set; }
    }
}