// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMOVIA.Entities.Entities
{
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbColaboradores = new HashSet<tbColaboradores>();
        }

        public int civi_Id { get; set; }
        public string civi_Descripcion { get; set; }
        public int civi_UsuarioCreacion { get; set; }
        public DateTime? civi_FechaCreacion { get; set; }
        public int? civi_UsuarioModificacion { get; set; }
        public DateTime? civi_FechaModificacion { get; set; }
        public bool? civi_Estado { get; set; }

        public virtual tbUsuarios civi_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbColaboradores> tbColaboradores { get; set; }
    }
}