// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMOVIA.Entities.Entities
{
    public partial class tbMunicipios
    {
        public tbMunicipios()
        {
            tbColaboradores = new HashSet<tbColaboradores>();
            tbSucursales = new HashSet<tbSucursales>();
        }

        public int muni_Id { get; set; }
        public string muni_Codigo { get; set; }
        public string muni_Descripcion { get; set; }
        public int depa_Id { get; set; }
        public int muni_UsuarioCreacion { get; set; }
        public DateTime muni_FechaCreacion { get; set; }
        public int? muni_UsuarioModificacion { get; set; }
        public DateTime? muni_FechaModificiacion { get; set; }

        public virtual tbDepartamentos depa { get; set; }
        public virtual tbUsuarios muni_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbColaboradores> tbColaboradores { get; set; }
        public virtual ICollection<tbSucursales> tbSucursales { get; set; }
    }
}