// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMOVIA.Entities.Entities
{
    public partial class tbPantallas
    {
        public tbPantallas()
        {
            tbPantallasPorRoles = new HashSet<tbPantallasPorRoles>();
        }

        public int pant_Id { get; set; }
        public string pant_Descripcion { get; set; }
        public string pant_direccionURL { get; set; }
        public int pant_UsuarioCreacion { get; set; }
        public DateTime pant_FechaCreacion { get; set; }
        public int? pant_UsuarioModificacion { get; set; }
        public DateTime? pant_FechaModificacion { get; set; }
        public bool? pant_Estado { get; set; }

        public virtual tbUsuarios pant_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios pant_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRoles { get; set; }
    }
}