// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMOVIA.Entities.Entities
{
    public partial class tbRoles
    {
        public tbRoles()
        {
            tbPantallasPorRoles = new HashSet<tbPantallasPorRoles>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int role_Id { get; set; }
        public string role_Descripcion { get; set; }
        public int role_UsuarioCreacion { get; set; }
        public DateTime? role_FechaCreacion { get; set; }
        public int? role_UsuarioModificacion { get; set; }
        public DateTime? role_FechaModificiacion { get; set; }
        public bool? role_Estado { get; set; }

        public virtual tbUsuarios role_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRoles { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}