// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMOVIA.Entities.Entities
{
    public partial class tbSucursales
    {
        public tbSucursales()
        {
            tbColaboradoresPorSucursal = new HashSet<tbColaboradoresPorSucursal>();
            tbViajesEncabezado = new HashSet<tbViajesEncabezado>();
        }

        //LISTAR
        public string codigo { get; set; }
        public string muni_Descripcion { get; set; }

        //TABLA
        public int sucu_Id { get; set; }
        public string sucu_Descripcion { get; set; }
        public string sucu_Direccion { get; set; }
        public string sucu_Telefono { get; set; }
        public int muni_Id { get; set; }
        public int sucu_UsuarioCreacion { get; set; }
        public DateTime sucu_FechaCreacion { get; set; }
        public int? sucu_UsuarioModificacion { get; set; }
        public DateTime? sucu_FechaModificacion { get; set; }
        public bool? sucu_Estado { get; set; }

        public virtual tbMunicipios muni { get; set; }
        public virtual tbUsuarios sucu_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios sucu_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbColaboradoresPorSucursal> tbColaboradoresPorSucursal { get; set; }
        public virtual ICollection<tbViajesEncabezado> tbViajesEncabezado { get; set; }
    }
}