// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMOVIA.Entities.Entities
{
    public partial class tbTransportistas
    {
        public tbTransportistas()
        {
            tbViajesEncabezado = new HashSet<tbViajesEncabezado>();
        }

        public int tran_Id { get; set; }
        public string tran_DNI { get; set; }
        public string tran_Nombre { get; set; }
        public string tran_Apellido { get; set; }
        public string tran_Telefono { get; set; }
        public decimal? tran_Tarifa { get; set; }
        public int tran_UsuarioCreacion { get; set; }
        public DateTime? tran_FechaCreacion { get; set; }
        public int? tran_UsuarioModificacion { get; set; }
        public DateTime? tran_FechaModificacion { get; set; }
        public bool? tran_Estado { get; set; }

        public virtual tbUsuarios tran_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios tran_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbViajesEncabezado> tbViajesEncabezado { get; set; }
    }
}