// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMOVIA.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            Inverseusua_UsuarioModificacionNavigation = new HashSet<tbUsuarios>();
            tbCargos = new HashSet<tbCargos>();
            tbColaboradores = new HashSet<tbColaboradores>();
            tbDepartamentos = new HashSet<tbDepartamentos>();
            tbEstadosCiviles = new HashSet<tbEstadosCiviles>();
            tbMunicipios = new HashSet<tbMunicipios>();
            tbPantallaspant_UsuarioCreacionNavigation = new HashSet<tbPantallas>();
            tbPantallaspant_UsuarioModificacionNavigation = new HashSet<tbPantallas>();
            tbRoles = new HashSet<tbRoles>();
            tbSucursalessucu_UsuarioCreacionNavigation = new HashSet<tbSucursales>();
            tbSucursalessucu_UsuarioModificacionNavigation = new HashSet<tbSucursales>();
            tbTransportistastran_UsuarioCreacionNavigation = new HashSet<tbTransportistas>();
            tbTransportistastran_UsuarioModificacionNavigation = new HashSet<tbTransportistas>();
            tbViajesEncabezadovien_UsuarioCreacionNavigation = new HashSet<tbViajesEncabezado>();
            tbViajesEncabezadovien_UsuarioModificacionNavigation = new HashSet<tbViajesEncabezado>();
        }

        public int usua_Id { get; set; }
        public string usua_Usuario { get; set; }
        public byte[] usua_Clave { get; set; }
        public bool usua_EsAdministrador { get; set; }
        public string usua_ObservacionActivar { get; set; }
        public string usua_ObservacionInactivar { get; set; }
        public string usua_CodigoReestablecer { get; set; }
        public int cola_Id { get; set; }
        public int role_Id { get; set; }
        public int? usua_UsuarioCreacion { get; set; }
        public DateTime? usua_FechaCreacion { get; set; }
        public int? usua_UsuarioModificacion { get; set; }
        public DateTime? usua_FechaModificacion { get; set; }
        public bool? usua_Estado { get; set; }

        public virtual tbColaboradores cola { get; set; }
        public virtual tbRoles role { get; set; }
        public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusua_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargos { get; set; }
        public virtual ICollection<tbColaboradores> tbColaboradores { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentos { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCiviles { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipios { get; set; }
        public virtual ICollection<tbPantallas> tbPantallaspant_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallaspant_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRoles { get; set; }
        public virtual ICollection<tbSucursales> tbSucursalessucu_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbSucursales> tbSucursalessucu_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbTransportistas> tbTransportistastran_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbTransportistas> tbTransportistastran_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbViajesEncabezado> tbViajesEncabezadovien_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbViajesEncabezado> tbViajesEncabezadovien_UsuarioModificacionNavigation { get; set; }
    }
}