// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMOVIA.Entities.Entities
{
    public partial class tbViajesEncabezado
    {
        public tbViajesEncabezado()
        {
            tbViajesDetalle = new HashSet<tbViajesDetalle>();
        }

        //LISTAR
        public string codigo { get; set; }
        public string transportista { get; set; }
        public string sucursal { get; set; }

        public int vien_Id { get; set; }
        public DateTime vien_Fecha { get; set; }
        public int vien_DistanciaTotalkm { get; set; }
        public decimal vien_TarifaTransportista { get; set; }
        public decimal vien_Total { get; set; }
        public int sucu_Id { get; set; }
        public int tran_Id { get; set; }
        public int vien_UsuarioCreacion { get; set; }
        public DateTime vien_FechaCreacion { get; set; }
        public int? vien_UsuarioModificacion { get; set; }
        public DateTime? vien_FechaModificacion { get; set; }
        public bool? vien_Estado { get; set; }

        public virtual tbSucursales sucu { get; set; }
        public virtual tbTransportistas tran { get; set; }
        public virtual tbUsuarios vien_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios vien_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbViajesDetalle> tbViajesDetalle { get; set; }
    }
}