// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIMOVIA.Entities.Entities
{
    public partial class tbViajesDetalle
    {
        public int vide_Id { get; set; }
        public int vien_Id { get; set; }
        public int cola_Id { get; set; }

        public virtual tbColaboradores cola { get; set; }
        public virtual tbViajesEncabezado vien { get; set; }
    }
}